repos:
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.30.0'
    hooks:
        - id: yapf
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
        - id: flake8
          args: [--append-config=tox.ini]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.790'
    hooks:
        - id: mypy
          args: [--no-strict-optional, --ignore-missing-imports]
