name: pixel2vec
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - click
  - h5py
  - hdf5
  - ignite
  - pillow
  - pip
  - python
  - pytorch-cuda
  - pyyaml
  - numpy
  - torchvision
  - tqdm
  - yaml
  - scikit-learn
  - pandas
  - seaborn
  - pip:
      - opencv-python
      - pytest
      - flake8
      - livelossplot
      - yapf
      - mypy
      - psutil
      - git+https://github.com/stared/pytorch-named-dims
      - pre-commit
      - ipython
      - isort
      - jupyter
      - gitpython
