name: Formatting python code
on:
  push:
    paths:
    - '**.py'
  pull_request:
    branches: [ master ]
jobs:
  autoyapf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install isort
          pip install yapf
      - name: autoisort
        shell: bash -l {0}
        run: |
          isort .
      - name: autoyapf
        id: autoyapf
        uses: mritunjaysharma394/autoyapf@v2
        with:
          args: --recursive --in-place .
      - name: Push changes if any file changed
        if: $(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi) == 'true'
        run: |
          git config --global user.name 'Autoformatting'
          git config --global user.email 'bartolo1024@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated autoyapf and autoisort fixes"
          git push
